### ISSUE TITLE
HW3ISSUE#4: Container issue

### ISSUE THREAD

**Issue by DennyTim** [RohitSavalagi/flexAndGrid#4]
If you wanna use width restrictions for the page, you need to use the following structure:

```html
<header class="...">
   <div class="container">...</div>
</header>
<main class="...">
   <div class="container">...</div>
</main >
<footer class="...">
   <div class="container">...</div>
</footer>
```

```css
.container {
    width: 960px;
    margin: 0 auto;
    text-align: center; /* can be used optionally if you wanna align the whole section */
}
```
